### ISSUE TITLE
Every member should use their own GITHUB id to commit changes to the repo

### ISSUE THREAD

**Issue by kgashok** [GaneshM35/awpa#10]
For e.g. updates to the Task List, Divya and Alagammai must make changes to the file and commit those changes using their GITHUB ids, and not use Ganesh's ID. 

Ask each of your team members to comment on this issue, and then close it.

**Comment by appu18** [comment]
Noted Sir

**Comment by divyamadhesh** [comment]
Noted Sir

**Comment by ALAGUVRM** [comment]
Noted Sir.

**Comment by GaneshM35** [comment]
Informed Sir.
