### ISSUE TITLE
Anna University network issues handling

### ISSUE THREAD

**Issue by kgashok** [GaneshM35/awpa#9]
How will the project gracefully handle network problems faced on the Anna Univ portal?

**Comment by GaneshM35** [comment]
The bot runs well in the normal internet connection and waits for webpage to load completely on the slow internet connection.

**Comment by kgashok** [comment]
No code changes?

**Comment by GaneshM35** [comment]
Sir,
Additional properties were added to the Bot to adopt live site (Live.xaml file) to handle slow internet connection

**Comment by kgashok** [comment]
This https://github.com/GaneshM35/awpa/commit/e5ce9fefc4c104dad186fb6f978ac2c47cf57abf commit brought in new additional file [Live.xaml](https://github.com/GaneshM35/awpa/blob/master/Application/Live.xaml).
